<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <AssemblyName>BlazorMemoire.Components</AssemblyName>
    <RootNamespace>BlazorMemoire.Components</RootNamespace>
    <PackageId>BlazorMemoire</PackageId>
    <Description>A highly-performant Blazor memo component, similar to React.memo, that freezes its child subtree until explicit dependency keys change, preventing unnecessary re-renders and making lifecycle methods fire only when there's been a true change.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/matthetherington/Blazor-Memoire</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>blazor;memoisation;memo;components;performance</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/matthetherington/Blazor-Memoire</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- See https://github.com/dotnet/razor/issues/13184 -->
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <SupportedPlatform Include="browser" />
    <InternalsVisibleTo Include="BlazorMemoire.Components.Tests" />
    <InternalsVisibleTo Include="BlazorMemoire.Components.Benchmarks" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\CHANGELOG.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
